services:
  db:
    container_name: mysql_storage
    image: mysql:latest
    platform: linux/x86_64
    volumes:
      - "/Users/austinrafter/PycharmProjects/ElectriciansDatabaseProject1/SQL-for-database/release_sql_for_database.sql:/docker-entrypoint-initdb.d/release_sql_for_database.sql"
    restart: always
    environment:
      - "MYSQL_DATABASE=SJELectricDatabase"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=ThisIsMyPassword"
      - "MYSQL_PASSWORD=ThisIsMyPassword"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_HOST: 0.0.0.0"
    ports:
      - "32000:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  flaskapi:
    build: ./flaskapi
    image: react-flask-app-api
    ports:
      - "5000:5000"
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASSWORD=ThisIsMyPassword"
      - "DB_NAME=SJELectricDatabase"
      - "DB_PORT=3306"
      - "CLIENT_ORIGIN=http://127.0.0.1:8888"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/ThisIsMyPassword
  client:
    build:
      context: .
      dockerfile: flask-react-app/Dockerfile.client
    image: react-flask-app-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
# Names our volume
volumes:
  SQL-for-database: