FROM node:16-alpine
WORKDIR /Users/austinrafter/PycharmProjects/ElectriciansDatabaseProject1/flask-react-app
ENV PATH C:\Users\Austin\PycharmProjects\ElectriciansDatabaseProject1\flask-react-app\node_modules\.bin:$PATH
COPY flask-react-app/public  /Users/austinrafter/PycharmProjects/ElectriciansDatabaseProject1/flask-react-app/public
COPY flask-react-app/src /Users/austinrafter/PycharmProjects/ElectriciansDatabaseProject1/flask-react-app/src
COPY flask-react-app/package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm" , "start"]