CREATE TABLE JOB_SITE (JOB_SITE_ID INTEGER NOT NULL AUTO_INCREMENT,
SITE_NAME VARCHAR(256) NOT NULL,
LOCATION_ID INTEGER NOT NULL,
START_DATE DATE NOT NULL,
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
PRIMARY KEY(JOB_SITE_ID));

CREATE TABLE LOCATION (LOCATION_ID INTEGER NOT NULL AUTO_INCREMENT,
LOCATION_NAME VARCHAR(256) NOT NULL,
PRIMARY KEY(LOCATION_ID));

CREATE TABLE CITY_STATE_ZIP (CITY_STATE_ZIP_ID INTEGER NOT NULL AUTO_INCREMENT,
CITY VARCHAR(128) NOT NULL,
STATE VARCHAR(50) NOT NULL,
ZIPCODE INTEGER NOT NULL,
PRIMARY KEY(CITY_STATE_ZIP_ID));

CREATE TABLE PERSON (PERSON_ID INTEGER NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(128) NOT NULL,
LAST_NAME VARCHAR(128) NOT NULL,
ADDRESS VARCHAR(256) NOT NULL,
CITY_STATE_ZIP_ID INTEGER NOT NULL,
PRIMARY KEY(PERSON_ID),
FOREIGN KEY(CITY_STATE_ZIP_ID) REFERENCES CITY_STATE_ZIP(CITY_STATE_ZIP_ID));

CREATE TABLE EMPLOYEE_POSITION (POSITION_ID INTEGER NOT NULL AUTO_INCREMENT,
POSITION_NAME VARCHAR(128) NOT NULL,
PRIMARY KEY(POSITION_ID));

CREATE TABLE ELECTRICIAN (ELECTRICIAN_ID INTEGER NOT NULL AUTO_INCREMENT,
PERSON_ID INTEGER NOT NULL,
POSITION_ID INTEGER NOT NULL,
YEARS_EMPLOYED INTEGER NOT NULL,
HOURLY_RATE FLOAT(25) NOT NULL,
PRIMARY KEY(ELECTRICIAN_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID),
FOREIGN KEY(POSITION_ID) REFERENCES EMPLOYEE_POSITION(POSITION_ID) );


CREATE TABLE INVENTORY (INVENTORY_ID INTEGER NOT NULL AUTO_INCREMENT,
MATERIAL_NAME VARCHAR(256) NOT NULL UNIQUE,
COST_PER_UNIT FLOAT(25) NOT NULL,
WEIGHT_PER_UNIT FLOAT(25) NOT NULL,
PRIMARY KEY(INVENTORY_ID));

CREATE TABLE ELECTRICIAN_ON_JOB (ELECTRICIAN_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
ELECTRICIAN_ID INTEGER NOT NULL,
PRIMARY KEY(ELECTRICIAN_ON_JOB_ID),
FOREIGN KEY (JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID),
FOREIGN KEY (ELECTRICIAN_ID) REFERENCES ELECTRICIAN(ELECTRICIAN_ID));

CREATE TABLE WORK_PACKAGE (WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
WORK_PACKAGE_NAME VARCHAR(256) NOT NULL,
PRICE_OF_WORK FLOAT(25) NOT NULL,
HOURS_ALLOTED INTEGER NOT NULL,
HOURS_USED INTEGER NOT NULL,
PRIMARY KEY(WORK_PACKAGE_ID),
FOREIGN KEY(JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID));

CREATE TABLE MATERIAL_IN_WORK_PACKAGE(MATERIAL_IN_WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
WORK_PACKAGE_ID INTEGER NOT NULL,
INVENTORY_ID INTEGER NOT NULL,
AMOUNT_ALLOTED INTEGER NOT NULL,
AMOUNT_USED INTEGER NOT NULL,
PRIMARY KEY(MATERIAL_IN_WORK_PACKAGE_ID),
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID),
FOREIGN KEY(INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID));

CREATE TABLE WORK_PACKAGE_ON_JOB_SITE (WORK_PACKAGE_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
WORK_PACKAGE_ID INTEGER NOT NULL,
PRIMARY KEY(WORK_PACKAGE_ON_JOB_ID),
FOREIGN KEY(JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID),
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID));

CREATE TABLE ELECTRICIAN_ON_WORK_PACKAGE (ELECTRICIAN_ON_WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
ELECTRICIAN_ID INTEGER NOT NULL,
WORK_PACKAGE_ID INTEGER NOT NULL,
PRIMARY KEY(ELECTRICIAN_ON_WORK_PACKAGE_ID),
FOREIGN KEY(ELECTRICIAN_ID) REFERENCES ELECTRICIAN(ELECTRICIAN_ID),
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID));

CREATE TABLE SALARIED_EMPLOYEE (SALARIED_EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
PERSON_ID INTEGER NOT NULL,
POSITION_ID INTEGER NOT NULL,
YEARS_EMPLOYED INTEGER NOT NULL,
HOURLY_RATE FLOAT(25) NOT NULL,
PRIMARY KEY(SALARIED_EMPLOYEE_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID),
FOREIGN KEY(POSITION_ID) REFERENCES EMPLOYEE_POSITION(POSITION_ID) );

CREATE TABLE SALARIED_EMPLOYEE_ON_JOB (SALARIED_EMPLOYEE_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
SALARIED_EMPLOYEE_ID INTEGER NOT NULL,
PRIMARY KEY(SALARIED_EMPLOYEE_ON_JOB_ID),
FOREIGN KEY (JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID),
FOREIGN KEY (SALARIED_EMPLOYEE_ID) REFERENCES SALARIED_EMPLOYEE(SALARIED_EMPLOYEE_ID));

CREATE VIEW GENERAL_MANAGER AS
SELECT SUM(PROJECT_MANAGER.WORK_PACKAGE_COST) AS COST_OF_PROJECT, SUM(PROJECT_MANAGER.AMOUNT_MADE_FOR_WORK_PACKAGE) AS AMOUNT_MADE_ON_PROJECT,
SUM(PROJECT_MANAGER.AMOUNT_MADE_FOR_WORK_PACKAGE)-SUM(PROJECT_MANAGER.WORK_PACKAGE_COST) AS TOTAL_PROFITS_ON_PROJECT,
CURDATE()-JOB_SITE.START_DATE AS NUMBER_OF_DAYS_ON_PROJECT
FROM PROJECT_MANAGER, WORK_PACKAGE, JOB_SITE
WHERE WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID
AND WORK_PACKAGE.WORK_PACKAGE_NAME = PROJECT_MANAGER.WORK_PACKAGE_NAME;

CREATE VIEW PROJECT_MANAGER AS
SELECT WORK_PACKAGE.WORK_PACKAGE_NAME,WORK_PACKAGE.HOURS_USED,(INVENTORY.COST_PER_UNIT * MATERIAL_IN_WORK_PACKAGE.AMOUNT_USED) AS MATERIAL_COST,
(SUM(ELECTRICIAN.HOURLY_RATE)*((WORK_PACKAGE.HOURS_USED)/COUNT(ELECTRICIAN.ELECTRICIAN_ID))) + (INVENTORY.COST_PER_UNIT * MATERIAL_IN_WORK_PACKAGE.AMOUNT_ALLOTED) AS WORK_PACKAGE_COST,
WORK_PACKAGE.PRICE_OF_WORK AS AMOUNT_MADE_FOR_WORK_PACKAGE, WORK_PACKAGE.PRICE_OF_WORK - ( (SUM(ELECTRICIAN.HOURLY_RATE)* ((WORK_PACKAGE.HOURS_USED)/COUNT(ELECTRICIAN.ELECTRICIAN_ID))) + (INVENTORY.COST_PER_UNIT * MATERIAL_IN_WORK_PACKAGE.AMOUNT_USED))
AS TOTAL_PROFITS, JOB_SITE.SITE_NAME
FROM ELECTRICIAN_ON_WORK_PACKAGE, MATERIAL_IN_WORK_PACKAGE, WORK_PACKAGE, ELECTRICIAN, INVENTORY, JOB_SITE
WHERE  ELECTRICIAN.ELECTRICIAN_ID = ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID
AND WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID
AND MATERIAL_IN_WORK_PACKAGE.WORK_PACKAGE_ID = WORK_PACKAGE.WORK_PACKAGE_ID
AND MATERIAL_IN_WORK_PACKAGE.INVENTORY_ID = INVENTORY.INVENTORY_ID
AND WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID;

CREATE VIEW FOREMAN AS
SELECT JOB_SITE.SITE_NAME,WORK_PACKAGE.WORK_PACKAGE_NAME, PERSON.FIRST_NAME, PERSON.LAST_NAME, (WORK_PACKAGE.HOURS_ALLOTED/ COUNT(ELECTRICIAN.ELECTRICIAN_ID)) AS INDIVIDUAL_HOURS_ALLOTED
FROM ELECTRICIAN, WORK_PACKAGE, ELECTRICIAN_ON_WORK_PACKAGE, PERSON, JOB_SITE
WHERE ELECTRICIAN.ELECTRICIAN_ID = ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID
AND WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID
AND ELECTRICIAN.PERSON_ID = PERSON.PERSON_ID
AND WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID;






