CREATE DATABASE TestDB4;

USE TestDB4;

CREATE TABLE LOCATION (LOCATION_ID INTEGER NOT NULL AUTO_INCREMENT,
LOCATION_NAME VARCHAR(256) NOT NULL,
PRIMARY KEY(LOCATION_ID));

CREATE TABLE CITY_STATE_ZIP (CITY_STATE_ZIP_ID INTEGER NOT NULL AUTO_INCREMENT,
CITY VARCHAR(128) NOT NULL,
STATE VARCHAR(50) NOT NULL,
ZIPCODE INTEGER NOT NULL,
PRIMARY KEY(CITY_STATE_ZIP_ID));

CREATE TABLE PERSON (PERSON_ID INTEGER NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(128) NOT NULL,
LAST_NAME VARCHAR(128) NOT NULL,
ADDRESS VARCHAR(256) NOT NULL,
CITY_STATE_ZIP_ID INTEGER NOT NULL,
PRIMARY KEY(PERSON_ID),
FOREIGN KEY(CITY_STATE_ZIP_ID) REFERENCES CITY_STATE_ZIP(CITY_STATE_ZIP_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE EMPLOYEE_POSITION (POSITION_ID INTEGER NOT NULL AUTO_INCREMENT,
POSITION_NAME VARCHAR(128) NOT NULL,
PRIMARY KEY(POSITION_ID));

CREATE TABLE INVENTORY (INVENTORY_ID INTEGER NOT NULL AUTO_INCREMENT,
MATERIAL_NAME VARCHAR(256) NOT NULL UNIQUE,
COST_PER_UNIT FLOAT(25) NOT NULL,
WEIGHT_PER_UNIT FLOAT(25) NOT NULL,
PRIMARY KEY(INVENTORY_ID));

CREATE TABLE JOB_SITE (JOB_SITE_ID INTEGER NOT NULL AUTO_INCREMENT,
SITE_NAME VARCHAR(256) NOT NULL,
LOCATION_ID INTEGER NOT NULL,
START_DATE DATE NOT NULL,
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(JOB_SITE_ID));

CREATE TABLE WORK_PACKAGE (WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
WORK_PACKAGE_NAME VARCHAR(256) NOT NULL,
PRICE_OF_WORK FLOAT(25) NOT NULL,
HOURS_ALLOTED INTEGER NOT NULL,
HOURS_USED INTEGER NOT NULL,
PRIMARY KEY(WORK_PACKAGE_ID),
FOREIGN KEY(JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ELECTRICIAN (ELECTRICIAN_ID INTEGER NOT NULL AUTO_INCREMENT,
PERSON_ID INTEGER NOT NULL,
POSITION_ID INTEGER NOT NULL,
YEARS_EMPLOYED INTEGER NOT NULL,
HOURLY_RATE FLOAT(25) NOT NULL,
PRIMARY KEY(ELECTRICIAN_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(POSITION_ID) REFERENCES EMPLOYEE_POSITION(POSITION_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE SALARIED_EMPLOYEE (SALARIED_EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
PERSON_ID INTEGER NOT NULL,
POSITION_ID INTEGER NOT NULL,
YEARS_EMPLOYED INTEGER NOT NULL,
SALARY_RATE FLOAT(25) NOT NULL,
PRIMARY KEY(SALARIED_EMPLOYEE_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(POSITION_ID) REFERENCES EMPLOYEE_POSITION(POSITION_ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE ELECTRICIAN_ON_JOB (ELECTRICIAN_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
ELECTRICIAN_ID INTEGER NOT NULL,
PRIMARY KEY(ELECTRICIAN_ON_JOB_ID),
FOREIGN KEY (JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ELECTRICIAN_ID) REFERENCES ELECTRICIAN(ELECTRICIAN_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE MATERIAL_IN_WORK_PACKAGE(MATERIAL_IN_WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
WORK_PACKAGE_ID INTEGER NOT NULL,
INVENTORY_ID INTEGER NOT NULL,
AMOUNT_ALLOTED INTEGER NOT NULL,
AMOUNT_USED INTEGER NOT NULL,
PRIMARY KEY(MATERIAL_IN_WORK_PACKAGE_ID),
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE WORK_PACKAGE_ON_JOB_SITE (WORK_PACKAGE_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
WORK_PACKAGE_ID INTEGER NOT NULL,
PRIMARY KEY(WORK_PACKAGE_ON_JOB_ID),
FOREIGN KEY(JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ELECTRICIAN_ON_WORK_PACKAGE (ELECTRICIAN_ON_WORK_PACKAGE_ID INTEGER NOT NULL AUTO_INCREMENT,
ELECTRICIAN_ID INTEGER NOT NULL,
WORK_PACKAGE_ID INTEGER NOT NULL,
PRIMARY KEY(ELECTRICIAN_ON_WORK_PACKAGE_ID),
FOREIGN KEY(ELECTRICIAN_ID) REFERENCES ELECTRICIAN(ELECTRICIAN_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(WORK_PACKAGE_ID) REFERENCES WORK_PACKAGE(WORK_PACKAGE_ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE SALARIED_EMPLOYEE_ON_JOB (SALARIED_EMPLOYEE_ON_JOB_ID INTEGER NOT NULL AUTO_INCREMENT,
JOB_SITE_ID INTEGER NOT NULL,
SALARIED_EMPLOYEE_ID INTEGER NOT NULL,
PRIMARY KEY(SALARIED_EMPLOYEE_ON_JOB_ID),
FOREIGN KEY (JOB_SITE_ID) REFERENCES JOB_SITE(JOB_SITE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (SALARIED_EMPLOYEE_ID) REFERENCES SALARIED_EMPLOYEE(SALARIED_EMPLOYEE_ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE VIEW PROJECT_MANAGER AS
SELECT WORK_PACKAGE.WORK_PACKAGE_NAME,WORK_PACKAGE.HOURS_USED, JOB_SITE.SITE_NAME,
(( SELECT INVENTORY.COST_PER_UNIT FROM INVENTORY WHERE INVENTORY.INVENTORY_ID = MATERIAL_IN_WORK_PACKAGE.INVENTORY_ID AND material_in_work_package.WORK_PACKAGE_ID = work_package.WORK_PACKAGE_ID)
* MATERIAL_IN_WORK_PACKAGE.AMOUNT_USED) AS MATERIAL_COST,
((SELECT SUM(ELECTRICIAN.HOURLY_RATE) FROM ELECTRICIAN_ON_WORK_PACKAGE, electrician WHERE WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID)
*((WORK_PACKAGE.HOURS_USED)/(SELECT COUNT(ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID)
FROM ELECTRICIAN_ON_WORK_PACKAGE,WORK_PACKAGE WHERE WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID)))
+ (INVENTORY.COST_PER_UNIT * MATERIAL_IN_WORK_PACKAGE.AMOUNT_ALLOTED) AS WORK_PACKAGE_COST,
WORK_PACKAGE.PRICE_OF_WORK AS AMOUNT_MADE_FOR_WORK_PACKAGE, WORK_PACKAGE.PRICE_OF_WORK -
(((SELECT SUM(ELECTRICIAN.HOURLY_RATE) FROM ELECTRICIAN_ON_WORK_PACKAGE, electrician WHERE WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID)
*((WORK_PACKAGE.HOURS_USED)/(SELECT COUNT(ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID)
FROM ELECTRICIAN_ON_WORK_PACKAGE,WORK_PACKAGE WHERE WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID)))
+ (INVENTORY.COST_PER_UNIT * MATERIAL_IN_WORK_PACKAGE.AMOUNT_ALLOTED))
AS TOTAL_PROFITS
FROM ELECTRICIAN_ON_WORK_PACKAGE
JOIN ELECTRICIAN ON  ELECTRICIAN.ELECTRICIAN_ID = ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID
JOIN WORK_PACKAGE ON WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID
JOIN MATERIAL_IN_WORK_PACKAGE ON MATERIAL_IN_WORK_PACKAGE.WORK_PACKAGE_ID = WORK_PACKAGE.WORK_PACKAGE_ID
JOIN INVENTORY ON MATERIAL_IN_WORK_PACKAGE.INVENTORY_ID = INVENTORY.INVENTORY_ID
JOIN JOB_SITE ON WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID;

CREATE VIEW FOREMAN AS
SELECT JOB_SITE.SITE_NAME,WORK_PACKAGE.WORK_PACKAGE_NAME, PERSON.FIRST_NAME, PERSON.LAST_NAME,
(WORK_PACKAGE.HOURS_ALLOTED/  (SELECT COUNT(ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID) FROM ELECTRICIAN_ON_WORK_PACKAGE WHERE WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID))
AS INDIVIDUAL_HOURS_ALLOTED
FROM electrician_on_work_package
JOIN ELECTRICIAN ON ELECTRICIAN.ELECTRICIAN_ID = ELECTRICIAN_ON_WORK_PACKAGE.ELECTRICIAN_ID
JOIN WORK_PACKAGE ON WORK_PACKAGE.WORK_PACKAGE_ID = ELECTRICIAN_ON_WORK_PACKAGE.WORK_PACKAGE_ID
JOIN person ON ELECTRICIAN.PERSON_ID = PERSON.PERSON_ID
JOIN JOB_SITE ON WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID;

CREATE VIEW GENERAL_MANAGER AS
SELECT SUM(PROJECT_MANAGER.WORK_PACKAGE_COST) AS COST_OF_PROJECT, SUM(PROJECT_MANAGER.AMOUNT_MADE_FOR_WORK_PACKAGE) AS AMOUNT_MADE_ON_PROJECT,
SUM(PROJECT_MANAGER.AMOUNT_MADE_FOR_WORK_PACKAGE)-SUM(PROJECT_MANAGER.WORK_PACKAGE_COST) AS TOTAL_PROFITS_ON_PROJECT,
CURDATE()-JOB_SITE.START_DATE AS NUMBER_OF_DAYS_ON_PROJECT
FROM PROJECT_MANAGER, WORK_PACKAGE, JOB_SITE
WHERE WORK_PACKAGE.JOB_SITE_ID = JOB_SITE.JOB_SITE_ID
AND WORK_PACKAGE.WORK_PACKAGE_NAME = PROJECT_MANAGER.WORK_PACKAGE_NAME;

INSERT INTO LOCATION (LOCATION_NAME) VALUES ("Palmia Apartments");
INSERT INTO LOCATION (LOCATION_NAME) VALUES ("Stoneridge Apartments");
INSERT INTO LOCATION (LOCATION_NAME) VALUES ("Cottle Apartments");
INSERT INTO LOCATION (LOCATION_NAME) VALUES ("Kaiser Permanente South San Francisco");

INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("Inside Wireman");
INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("Residential Wireman");
INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("Project Manager");
INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("Foreman");
INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("General Manager");
INSERT INTO EMPLOYEE_POSITION (POSITION_NAME) VALUES ("Project Engineer");

INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("San Jose", "California", 95123);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("San Jose", "California", 95002);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("San Jose", "California", 95127);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("Stockton", "California", 95210);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("Los Banos", "California", 93635);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("Oakland","California", 94601);
INSERT INTO CITY_STATE_ZIP (CITY,STATE,ZIPCODE) VALUES ("Oakland", "California", 94622);

INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Rick", "James", "123 Washington St", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 95123 AND STATE = "California" AND CITY= "San Jose"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Austin", "Rafter", "2274 Chestnut Dr", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 95002 AND STATE = "California" AND CITY= "San Jose"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("John", "Smith", "3421 Desert Rd", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 95210 AND STATE = "California" AND CITY= "Stockton"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Chifundo" , "Bonomo", "13979 Euna Rd", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 93635 AND STATE = "California" AND CITY= "Los Banos"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Garnett", "Fiddler", "95634 Josie Way", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 95127 AND STATE = "California" AND CITY= "San Jose"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Wilfreda" , "Nowell", "2319 Will Island Ave", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 94622 AND STATE = "California" AND CITY= "Oakland"));
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,ADDRESS, CITY_STATE_ZIP_ID) VALUES ("Kaylyn", "Morse", "111 Emmerich Summit, Apt", (SELECT CITY_STATE_ZIP_ID FROM CITY_STATE_ZIP WHERE ZIPCODE = 93635 AND STATE = "California" AND CITY= "Los Banos"));

INSERT INTO JOB_SITE (SITE_NAME,LOCATION_ID,START_DATE) VALUES ("Palmia Apartment Job", (SELECT LOCATION_ID FROM LOCATION WHERE LOCATION_NAME = "Palmia Apartments"), "2021-02-21");
INSERT INTO JOB_SITE (SITE_NAME,LOCATION_ID,START_DATE) VALUES ("Stoneridge Apartment Job", (SELECT LOCATION_ID FROM LOCATION WHERE LOCATION_NAME = "Stoneridge Apartments"), "2021-03-12");
INSERT INTO JOB_SITE (SITE_NAME,LOCATION_ID,START_DATE) VALUES ("Kaiser Permanente Building Job", (SELECT LOCATION_ID FROM LOCATION WHERE LOCATION_NAME = "Kaiser Permanente South San Francisco"), "2021-05-12");

 INSERT INTO INVENTORY (MATERIAL_NAME,COST_PER_UNIT,WEIGHT_PER_UNIT) VALUES ("Light Fixture", 8.50, 3.23);
 INSERT INTO INVENTORY (MATERIAL_NAME,COST_PER_UNIT,WEIGHT_PER_UNIT) VALUES ("Wire", 27.36, 17.23);
 INSERT INTO INVENTORY (MATERIAL_NAME,COST_PER_UNIT,WEIGHT_PER_UNIT) VALUES ("Outlet Plug", 8.47, 1.21);

INSERT INTO WORK_PACKAGE (JOB_SITE_ID ,WORK_PACKAGE_NAME ,PRICE_OF_WORK, HOURS_ALLOTED,HOURS_USED) VALUES ((SELECT JOB_SITE_ID FROM JOB_SITE WHERE SITE_NAME = "Palmia Apartment Job" AND START_DATE = "2021-02-21"), "Pull Wire", 2500.00, 15, 20);
INSERT INTO WORK_PACKAGE (JOB_SITE_ID ,WORK_PACKAGE_NAME ,PRICE_OF_WORK, HOURS_ALLOTED,HOURS_USED) VALUES ((SELECT JOB_SITE_ID FROM JOB_SITE WHERE SITE_NAME = "Palmia Apartment Job" AND START_DATE = "2021-02-21"), "Set Fixtures", 2300.00, 25, 23);

INSERT INTO ELECTRICIAN(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, HOURLY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "Rick" AND LAST_NAME = "James" AND ADDRESS = "123 Washington St"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "Residential Wireman") , 4, 23.50);
INSERT INTO ELECTRICIAN(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, HOURLY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "Austin" AND LAST_NAME = "Rafter" AND ADDRESS = "2274 Chestnut Dr"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "Residential Wireman") , 3,21.45);
INSERT INTO ELECTRICIAN(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, HOURLY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "John" AND LAST_NAME = "Smith" AND ADDRESS = "3421 Desert Rd"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "Inside Wireman") , 6,27.80);

INSERT INTO ELECTRICIAN_ON_WORK_PACKAGE(ELECTRICIAN_ID,WORK_PACKAGE_ID) VALUES ((SELECT ELECTRICIAN_ID FROM ELECTRICIAN WHERE PERSON_ID = 1), (SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 1));
INSERT INTO ELECTRICIAN_ON_WORK_PACKAGE(ELECTRICIAN_ID,WORK_PACKAGE_ID) VALUES ((SELECT ELECTRICIAN_ID FROM ELECTRICIAN WHERE PERSON_ID = 1), (SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 2));
INSERT INTO ELECTRICIAN_ON_WORK_PACKAGE(ELECTRICIAN_ID,WORK_PACKAGE_ID) VALUES ((SELECT ELECTRICIAN_ID FROM ELECTRICIAN WHERE PERSON_ID = 2), (SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 1));
INSERT INTO ELECTRICIAN_ON_WORK_PACKAGE(ELECTRICIAN_ID,WORK_PACKAGE_ID) VALUES ((SELECT ELECTRICIAN_ID FROM ELECTRICIAN WHERE PERSON_ID = 2), (SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 2));


INSERT INTO MATERIAL_IN_WORK_PACKAGE(WORK_PACKAGE_ID,INVENTORY_ID,AMOUNT_ALLOTED,AMOUNT_USED) VALUES ((SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 1),(SELECT INVENTORY_ID FROM INVENTORY WHERE INVENTORY_ID= 2),6,6);
INSERT INTO MATERIAL_IN_WORK_PACKAGE(WORK_PACKAGE_ID,INVENTORY_ID,AMOUNT_ALLOTED,AMOUNT_USED) VALUES ((SELECT WORK_PACKAGE_ID FROM WORK_PACKAGE WHERE WORK_PACKAGE_ID = 2),(SELECT INVENTORY_ID FROM INVENTORY WHERE INVENTORY_ID=1),15,13);

INSERT INTO SALARIED_EMPLOYEE(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, SALARY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "Chifundo" AND LAST_NAME = "Bonomo" AND ADDRESS = "13979 Euna Rd"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "Foreman") , 4, 75000.00);
INSERT INTO SALARIED_EMPLOYEE(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, SALARY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "Garnett" AND LAST_NAME = "Fiddler" AND ADDRESS = "95634 Josie Way"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "Project Manager") , 7, 108000.00);
INSERT INTO SALARIED_EMPLOYEE(PERSON_ID,POSITION_ID,YEARS_EMPLOYED, SALARY_RATE) VALUES ((SELECT PERSON_ID FROM PERSON WHERE FIRST_NAME = "Wilfreda" AND LAST_NAME = "Nowell" AND ADDRESS = "2319 Will Island Ave"),(SELECT POSITION_ID FROM EMPLOYEE_POSITION WHERE POSITION_NAME = "General Manager") , 13, 245000.00)







